const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const addonRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(addonRoot, '..');

const contract = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'contracts', 'editor-capability-matrix.json'), 'utf8')
);
const extensionSource = fs.readFileSync(path.join(addonRoot, 'src', 'extension.ts'), 'utf8');
const monitorSource = fs.readFileSync(path.join(addonRoot, 'src', 'statusMonitor.ts'), 'utf8');
const contractSource = fs.readFileSync(path.join(addonRoot, 'src', 'protocolContract.ts'), 'utf8');

assert.equal(contract.surfaces.vscodeAddon.supports.openAiCompat, true);
assert.equal(contract.surfaces.vscodeAddon.supports.responsesNative, false);
assert.deepEqual(contract.protocol.supportedModes, ['acp', 'mcp', 'auto']);
assert.equal(contract.protocol.defaultMode, 'auto');
assert.equal(contract.protocol.autoModeSupportsAcpAndMcp, true);
assert.equal(contract.protocol.acpInitializeProtocol, 'acp');
assert.equal(contract.protocol.mcpInitializeProtocolVersion, '2024-11-05');
assert.equal(contract.protocol.coexistenceValidatedByRpcIntegration, true);
assert.equal(contract.protocol.triPathValidatedByIntegration, true);
assert.equal(contract.protocol.httpRootSupportsAcpHttp, true);
assert.equal(contract.protocol.httpRootAdvertisesResponsesEndpoints, true);
assert.equal(contract.protocol.guiDetectsAutoModeLiteral, true);
assert.equal(contract.protocol.guiParsesProtocolModeFromProtocolSection, true);
assert.equal(contract.protocol.guiTauriCompileCheckedInMainChain, true);
assert.equal(contract.protocol.vscodeAddonCompileCheckedInMainChain, true);
assert.equal(contract.protocol.rpcFallbackDegradeCheckedInMainChain, true);
assert.equal(contract.protocol.rpcConfigReloadCheckedInMainChain, true);
assert.equal(contract.protocol.rpcReviewTimeoutCollisionCheckedInMainChain, true);
assert.equal(contract.protocol.rpcInitHealthShutdownCheckedInMainChain, true);
assert.equal(contract.protocol.httpStreamSseAndPersistenceCheckedInMainChain, true);
assert.equal(contract.protocol.rpcDebugPanelSnapshotCheckedInMainChain, true);
assert.equal(contract.protocol.rpcConversationCheckpointCheckedInMainChain, true);
assert.equal(contract.protocol.rpcCacheClearAndValidationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcRateLimitSaturationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcJsonRpcVersionValidationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcChatParameterValidationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcBreakerStatusAndResetCheckedInMainChain, true);
assert.equal(contract.protocol.startupFailureOnMissingDependenciesCheckedInMainChain, true);
assert.equal(contract.protocol.rpcLegacyMethodAliasesCompatibilityCheckedInMainChain, true);
assert.equal(contract.protocol.rpcActionVectorMaintenanceAndMetricsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcUnknownMethodAndConfigReloadCheckedInMainChain, true);
assert.equal(contract.protocol.rpcTaskGovernanceRequirementGateCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowReviewPolicyAndLearningFeedbackCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowDualReviewAndDecisionsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcLearningSummaryAggregatesMetricsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcPrimarySecondaryPolicyArtifactCheckedInMainChain, true);
assert.equal(contract.protocol.rpcPrimarySecondaryStabilityFailoverCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowConsultArtifactAndConsensusCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowResearchArtifactAndPlanCheckedInMainChain, true);
assert.equal(contract.protocol.rpcConfirmClarificationRoundsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcAutotuneResetDefaultStateCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowAutoConsultationConsensusGateCheckedInMainChain, true);
assert.equal(contract.protocol.acpCoreUnitSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.i18nModuleSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.coreConfigUnitSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.governancePuaUnitSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.mcpModuleSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.protocolMcpServerSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.openaiCompatibleAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.memoryCacheSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.memoryVectorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationTaskRouterSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationFlowSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationFlowWithModelsSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationOrchestratorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationToolSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.coreErrorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.copilotAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.anthropicAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.qwenAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.wenxinAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.deepseekAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationCostSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationSpeedSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationReliabilitySuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationFailurePreventionSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceAdaptiveSelectorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceModelSelectorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceAdvancedModulesSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceReinforcementSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.coreSetupSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.genericAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.acpPreludeMetricsSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationSkillRegistrySuiteCheckedInMainChain, true);
assert.equal(contract.protocol.rustAllTargetsFullGateCheckedInMainChain, true);
assert.ok(contract.openai.commonForwardedFields.includes('parallel_tool_calls'));
assert.equal(contract.responsesApi.path, '/v1/responses');
assert.equal(contract.responsesApi.retrievalPath, '/v1/responses/{id}');
assert.equal(contract.responsesApi.listPath, '/v1/responses');
assert.equal(contract.responsesApi.responseRetrievalSupport, true);
assert.equal(contract.responsesApi.responseListSupport, true);
assert.equal(contract.responsesApi.responseListObjectType, 'list');
assert.equal(contract.responsesApi.responseListDataContainsResponseObjects, true);
assert.equal(contract.responsesApi.responseListNewestFirst, true);
assert.equal(contract.responsesApi.responseIdsAreUniquePerRequest, true);
assert.equal(contract.responsesApi.responseIdHasTimestampAndSequence, true);
assert.equal(contract.responsesApi.responseStoreTracksCompleted, true);
assert.equal(contract.responsesApi.responseStoreTracksFailed, true);
assert.deepEqual(contract.responsesApi.responseStatusLifecycle, ['queued', 'in_progress', 'completed', 'failed']);
assert.equal(contract.responsesApi.responseStatusHistoryField, 'status_history');
assert.equal(contract.responsesApi.responseHistoryIncludesTransitions, true);
assert.equal(contract.responsesApi.toolCallInitiationSupport, true);
assert.equal(contract.responsesApi.toolChoiceRequiredReturnsIncomplete, true);
assert.equal(contract.responsesApi.toolCallOutputItemSupport, true);
assert.equal(contract.responsesApi.toolResultContinuationSupport, true);
assert.equal(contract.responsesApi.previousResponseIdMustBeNonEmptyString, true);
assert.equal(contract.responsesApi.toolResultRequiresMatchingToolCallId, true);
assert.equal(contract.responsesApi.toolResultOutputItemSupport, true);
assert.deepEqual(contract.responsesApi.failureCodeClasses, ['timeout', 'rate_limit', 'tool_error', 'upstream_error']);
assert.equal(contract.responsesApi.toolLoopMissingResultUsesToolError, true);
assert.equal(contract.responsesApi.noPendingToolCallUsesToolError, true);
assert.equal(contract.responsesApi.upstreamTimeoutMapped, true);
assert.equal(contract.responsesApi.upstreamRateLimitMapped, true);
assert.equal(contract.responsesApi.retrievalNotFoundUsesResponsesErrorShape, true);
assert.equal(contract.responsesApi.errorHasCodeField, true);
assert.equal(contract.responsesApi.requestBodyMustBeObject, true);
assert.equal(contract.responsesApi.modelMustBeNonEmptyString, true);
assert.equal(contract.responsesApi.modelMustBeString, true);
assert.deepEqual(contract.responsesApi.acceptedInputTypes, ['string', 'array']);
assert.equal(contract.responsesApi.inputMustProduceMessages, true);
assert.equal(contract.responsesApi.inputMustIncludeUserMessage, true);
assert.equal(contract.responsesApi.maxOutputTokensMin, 1);
assert.equal(contract.responsesApi.maxOutputTokensMustBeInteger, true);
assert.equal(contract.responsesApi.temperatureMustBeNumber, true);
assert.deepEqual(contract.responsesApi.temperatureRange, [0, 2]);
assert.equal(contract.responsesApi.metadataMustBeObject, true);
assert.equal(contract.responsesApi.reasoningMustBeObject, true);
assert.equal(contract.responsesApi.toolsMustBeArray, true);
assert.equal(contract.responsesApi.toolsEntriesMustBeObjects, true);
assert.equal(contract.responsesApi.toolsEntriesMustUseFunctionType, true);
assert.equal(contract.responsesApi.toolsEntriesRequireFunctionName, true);
assert.equal(contract.responsesApi.toolsFunctionDescriptionMustBeString, true);
assert.equal(contract.responsesApi.toolsFunctionParametersMustBeObject, true);
assert.equal(contract.responsesApi.toolsFunctionParametersTypeMustBeObject, true);
assert.equal(contract.responsesApi.toolsFunctionParametersPropertiesMustBeObject, true);
assert.equal(contract.responsesApi.toolsFunctionParametersRequiredMustBeStringArray, true);
assert.deepEqual(contract.responsesApi.toolChoiceAllowedTypes, ['string', 'object']);
assert.deepEqual(contract.responsesApi.toolChoiceStringValues, ['auto', 'none', 'required']);
assert.equal(contract.responsesApi.toolChoiceRequiredNeedsTools, true);
assert.equal(contract.responsesApi.toolChoiceObjectMustUseFunctionType, true);
assert.equal(contract.responsesApi.toolChoiceObjectRequiresFunctionName, true);
assert.equal(contract.responsesApi.toolChoiceObjectRequiresTools, true);
assert.equal(contract.responsesApi.toolChoiceObjectMustReferenceDeclaredTool, true);
assert.equal(contract.responsesApi.emptyBodyUsesResponsesErrorShape, true);
assert.equal(contract.responsesApi.invalidJsonUsesResponsesErrorShape, true);
assert.equal(contract.responsesApi.goldenCasesImplemented, true);
assert.deepEqual(contract.responsesApi.responseRequiredFields, ['id', 'object', 'created_at', 'model', 'status', 'output', 'usage', 'error', 'incomplete_details']);
assert.deepEqual(contract.responsesApi.errorRequiredFields, ['code', 'type', 'message']);
assert.deepEqual(contract.responsesApi.streamEventOrder, ['response.created', 'response.output_text.delta', 'response.completed']);
assert.equal(contract.responsesApi.rootCapabilitiesPath, '/');
assert.equal(contract.responsesApi.rootCapabilitiesAdvertisesResponsesEndpoints, true);
assert.equal(contract.responsesApi.deleteResponseMethodReturns405, true);
assert.equal(contract.responsesApi.streamSetupUnavailableDegradesToCompleted, true);
assert.equal(contract.responsesApi.streamSetupUnavailableUsesDegradedMessage, true);
assert.equal(contract.responsesApi.streamSetupUnavailableStoredAsCompleted, true);
assert.equal(contract.responsesApi.streamSetupUnavailableRetrievableById, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableDegradesToCompleted, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableUsesDegradedMessage, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableStoredAsCompleted, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableRetrievableById, true);
assert.deepEqual(contract.responsesApi.streamEvents, ['response.created', 'response.output_text.delta', 'response.completed', 'response.failed']);
assert.equal(contract.responsesApi.streamTerminatesWithDone, true);
assert.ok(contractSource.includes('editor-capability-matrix.json'));
assert.ok(contractSource.includes('protocol: {'));
assert.ok(contractSource.includes('responsesApi: {'));
assert.ok(contractSource.includes('vscodeAddonCompileCheckedInMainChain: true'));
assert.ok(contractSource.includes('streamSetupUnavailableDegradesToCompleted: true'));
assert.ok(extensionSource.includes('protocolContract.errors.providerNotReady'));
assert.ok(extensionSource.includes('protocolContract.errors.setupWizardPrompt'));
assert.deepEqual(contract.errors.requestErrorKinds, ['PuaViolation', 'BudgetExceeded', 'SandboxBlocked']);
assert.equal(contract.errors.requestErrorContextPrefix, 'acp.handle_request.dispatch');
assert.ok(extensionSource.includes('formatRpcError'));
assert.ok(extensionSource.includes('rpc_error:'));
assert.ok(extensionSource.includes('protocolContract.errors.requestErrorContextPrefix'));
assert.ok(monitorSource.includes('protocolContract.statusTerms.healthy'));
assert.ok(monitorSource.includes('protocolContract.statusTerms.healthCheckFailed'));

console.log('VS Code addon contract smoke passed');
