import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const guiRoot = path.resolve(import.meta.dirname, '..');
const repoRoot = path.resolve(guiRoot, '..');

const contract = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'contracts', 'editor-capability-matrix.json'), 'utf8')
);
const apiSource = fs.readFileSync(path.join(guiRoot, 'src', 'services', 'api.ts'), 'utf8');
const protocolSource = fs.readFileSync(
    path.join(guiRoot, 'src', 'services', 'protocolContract.ts'),
    'utf8'
);
const tauriSource = fs.readFileSync(
    path.join(guiRoot, 'src-tauri', 'src', 'commands', 'integrations.rs'),
    'utf8'
);
const runtimeOpsSource = fs.readFileSync(
    path.join(guiRoot, 'src-tauri', 'src', 'commands', 'runtime_ops.rs'),
    'utf8'
);

assert.equal(contract.surfaces.gui.supports.openAiCompat, true);
assert.equal(contract.surfaces.gui.supports.responsesNative, false);
assert.equal(typeof contract.verification?.generatedBy, 'string');
assert.equal(typeof contract.verification?.generatedAt, 'string');
assert.equal(typeof contract.verification?.sourceOfTruth, 'string');
assert.ok(contract.verification.generatedBy.length > 0);
assert.ok(contract.verification.generatedAt.includes('T'));
assert.ok(contract.verification.sourceOfTruth.length > 0);
assert.deepEqual(contract.protocol.supportedModes, ['adaptive', 'acp_stdio', 'acp_http', 'mcp_stdio', 'mcp_http']);
assert.deepEqual(contract.protocol.workflowControlModes, ['manual', 'assisted', 'autonomous']);
assert.equal(contract.protocol.defaultWorkflowControlMode, 'assisted');
assert.equal(contract.protocol.defaultMode, 'adaptive');
assert.equal(contract.protocol.autoModeSupportsAcpAndMcp, true);
assert.equal(contract.protocol.protocolCapabilityModel, 'capability_plus_transport');
assert.equal(contract.protocol.adaptiveSelectionModel, 'client_type_routed');
assert.equal(contract.protocol.adaptiveStartupTransportStrategy, 'http_if_bind_else_stdio');
assert.equal(contract.protocol.fixedModesAreConfigDriven, true);
assert.equal(contract.protocol.acpInitializeProtocol, 'acp');
assert.equal(contract.protocol.mcpInitializeProtocolVersion, '2024-11-05');
assert.equal(contract.protocol.coexistenceValidatedByRpcIntegration, true);
assert.equal(contract.protocol.triPathValidatedByIntegration, true);
assert.equal(contract.protocol.httpRootSupportsAcpHttp, true);
assert.equal(contract.protocol.httpRootAdvertisesResponsesEndpoints, true);
assert.equal(contract.protocol.guiDetectsAutoModeLiteral, true);
assert.equal(contract.protocol.guiParsesProtocolModeFromProtocolSection, true);
assert.equal(contract.protocol.guiTauriCompileCheckedInMainChain, true);
assert.equal(contract.protocol.vscodeAddonCompileCheckedInMainChain, true);
assert.equal(contract.protocol.rpcFallbackDegradeCheckedInMainChain, true);
assert.equal(contract.protocol.rpcConfigReloadCheckedInMainChain, true);
assert.equal(contract.protocol.rpcReviewTimeoutCollisionCheckedInMainChain, true);
assert.equal(contract.protocol.rpcInitHealthShutdownCheckedInMainChain, true);
assert.equal(contract.protocol.httpStreamSseAndPersistenceCheckedInMainChain, true);
assert.equal(contract.protocol.rpcDebugPanelSnapshotCheckedInMainChain, true);
assert.equal(contract.protocol.rpcConversationCheckpointCheckedInMainChain, true);
assert.equal(contract.protocol.rpcCacheClearAndValidationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcRateLimitSaturationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcJsonRpcVersionValidationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcChatParameterValidationCheckedInMainChain, true);
assert.equal(contract.protocol.rpcBreakerStatusAndResetCheckedInMainChain, true);
assert.equal(contract.protocol.startupFailureOnMissingDependenciesCheckedInMainChain, true);
assert.equal(contract.protocol.rpcLegacyMethodAliasesCompatibilityCheckedInMainChain, true);
assert.equal(contract.protocol.rpcActionVectorMaintenanceAndMetricsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcUnknownMethodAndConfigReloadCheckedInMainChain, true);
assert.equal(contract.protocol.rpcTaskGovernanceRequirementGateCheckedInMainChain, true);
assert.equal(contract.protocol.rpcUnifiedGateFacadeCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowResearchConsultGateCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowTaskExecutionCycleCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowTaskChangeBundleCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowTaskResponseSkeletonCheckedInMainChain, true);
assert.equal(contract.protocol.rpcExecutionCycleHistoryAndAutoRepairPlanCheckedInMainChain, true);
assert.equal(contract.protocol.rpcExecutionCycleRealRepairIterationHistoryCheckedInMainChain, true);
assert.equal(contract.protocol.rpcChangeBundleRollbackCommitCoverageCheckedInMainChain, true);
assert.equal(contract.protocol.rpcRuntimeExecutionCyclePatchSetAndRepairPreviewCheckedInMainChain, true);
assert.equal(contract.protocol.rpcChangeBundleFileSummaryRiskGateRollbackCommitSuggestionCheckedInMainChain, true);
assert.equal(contract.protocol.toolRegistryCapabilityRiskTimeoutRetryFallbackCheckedInMainChain, true);
assert.equal(contract.protocol.toolFallbackExecutionChainCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowReviewPolicyAndLearningFeedbackCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowDualReviewAndDecisionsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcTaskPlanMemoryGraphRecallCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowTaskRunModeSwitchCheckedInMainChain, true);
assert.equal(contract.protocol.blue22BenchmarkSnapshotScriptCheckedInMainChain, true);
assert.equal(contract.protocol.blue22BenchmarkIndicatorsTrackedInMainChain, true);
assert.equal(contract.protocol.blue22ReleaseGateRunsBenchmarkSnapshotCheckedInMainChain, true);
assert.equal(contract.protocol.rpcLearningSummaryAggregatesMetricsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcPrimarySecondaryPolicyArtifactCheckedInMainChain, true);
assert.equal(contract.protocol.rpcPrimarySecondaryStabilityFailoverCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowConsultArtifactAndConsensusCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowResearchArtifactAndPlanCheckedInMainChain, true);
assert.equal(contract.protocol.rpcConfirmClarificationRoundsCheckedInMainChain, true);
assert.equal(contract.protocol.rpcAutotuneResetDefaultStateCheckedInMainChain, true);
assert.equal(contract.protocol.rpcWorkflowAutoConsultationConsensusGateCheckedInMainChain, true);
assert.equal(contract.protocol.acpCoreUnitSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.i18nModuleSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.coreConfigUnitSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.governancePuaUnitSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.mcpModuleSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.protocolMcpServerSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.openaiCompatibleAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.memoryCacheSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.memoryVectorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationTaskRouterSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationFlowSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationFlowWithModelsSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationOrchestratorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationToolSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.coreErrorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.copilotAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.anthropicAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.qwenAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.wenxinAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.deepseekAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationCostSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationSpeedSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationReliabilitySuiteCheckedInMainChain, true);
assert.equal(contract.protocol.optimizationFailurePreventionSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceAdaptiveSelectorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceModelSelectorSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceAdvancedModulesSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.intelligenceReinforcementSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.coreSetupSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.genericAgentSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.acpPreludeMetricsSuiteCheckedInMainChain, true);
assert.equal(contract.protocol.orchestrationSkillRegistrySuiteCheckedInMainChain, true);
assert.equal(contract.protocol.rustAllTargetsFullGateCheckedInMainChain, true);
assert.ok(tauriSource.includes('fn protocol_mode_from_config_text'));
assert.ok(tauriSource.includes('Some("protocol")'));
assert.ok(tauriSource.includes('Some("runtime")'));
assert.ok(tauriSource.includes('protocol_mode'));
assert.ok(
    tauriSource.includes('"auto" => Some("adaptive")') ||
    tauriSource.includes('"auto" => Some("auto")')
);
assert.ok(
    tauriSource.includes('Adaptive mode enabled; runtime chooses the best client-facing path and routes requests by client type')
);
assert.equal(contract.openai.streamDoneMarker, '[DONE]');
assert.equal(contract.responsesApi.path, '/v1/responses');
assert.equal(contract.responsesApi.retrievalPath, '/v1/responses/{id}');
assert.equal(contract.responsesApi.listPath, '/v1/responses');
assert.equal(contract.responsesApi.responseRetrievalSupport, true);
assert.equal(contract.responsesApi.responseListSupport, true);
assert.equal(contract.responsesApi.responseListObjectType, 'list');
assert.equal(contract.responsesApi.responseListDataContainsResponseObjects, true);
assert.equal(contract.responsesApi.responseListNewestFirst, true);
assert.equal(contract.responsesApi.responseIdsAreUniquePerRequest, true);
assert.equal(contract.responsesApi.responseIdHasTimestampAndSequence, true);
assert.equal(contract.responsesApi.responseStoreTracksCompleted, true);
assert.equal(contract.responsesApi.responseStoreTracksFailed, true);
assert.deepEqual(contract.responsesApi.responseStatusLifecycle, ['queued', 'in_progress', 'completed', 'failed']);
assert.equal(contract.responsesApi.responseStatusHistoryField, 'status_history');
assert.equal(contract.responsesApi.responseHistoryIncludesTransitions, true);
assert.equal(contract.responsesApi.toolCallInitiationSupport, true);
assert.equal(contract.responsesApi.toolChoiceRequiredReturnsIncomplete, true);
assert.equal(contract.responsesApi.toolCallOutputItemSupport, true);
assert.equal(contract.responsesApi.toolResultContinuationSupport, true);
assert.equal(contract.responsesApi.previousResponseIdMustBeNonEmptyString, true);
assert.equal(contract.responsesApi.toolResultRequiresMatchingToolCallId, true);
assert.equal(contract.responsesApi.toolResultOutputItemSupport, true);
assert.deepEqual(contract.responsesApi.failureCodeClasses, ['timeout', 'rate_limit', 'tool_error', 'upstream_error']);
assert.equal(contract.responsesApi.toolLoopMissingResultUsesToolError, true);
assert.equal(contract.responsesApi.noPendingToolCallUsesToolError, true);
assert.equal(contract.responsesApi.upstreamTimeoutMapped, true);
assert.equal(contract.responsesApi.upstreamRateLimitMapped, true);
assert.equal(contract.responsesApi.retrievalNotFoundUsesResponsesErrorShape, true);
assert.equal(contract.responsesApi.streamSupport, true);
assert.deepEqual(contract.responsesApi.streamEvents, ['response.created', 'response.output_text.delta', 'response.completed', 'response.failed']);
assert.equal(contract.responsesApi.streamTerminatesWithDone, true);
assert.equal(contract.responsesApi.requestBodyMustBeObject, true);
assert.equal(contract.responsesApi.modelMustBeNonEmptyString, true);
assert.equal(contract.responsesApi.modelMustBeString, true);
assert.deepEqual(contract.responsesApi.acceptedInputTypes, ['string', 'array']);
assert.equal(contract.responsesApi.inputMustProduceMessages, true);
assert.equal(contract.responsesApi.inputMustIncludeUserMessage, true);
assert.equal(contract.responsesApi.maxOutputTokensMin, 1);
assert.equal(contract.responsesApi.maxOutputTokensMustBeInteger, true);
assert.equal(contract.responsesApi.temperatureMustBeNumber, true);
assert.deepEqual(contract.responsesApi.temperatureRange, [0, 2]);
assert.equal(contract.responsesApi.metadataMustBeObject, true);
assert.equal(contract.responsesApi.reasoningMustBeObject, true);
assert.equal(contract.responsesApi.toolsMustBeArray, true);
assert.equal(contract.responsesApi.toolsEntriesMustBeObjects, true);
assert.equal(contract.responsesApi.toolsEntriesMustUseFunctionType, true);
assert.equal(contract.responsesApi.toolsEntriesRequireFunctionName, true);
assert.equal(contract.responsesApi.toolsFunctionDescriptionMustBeString, true);
assert.equal(contract.responsesApi.toolsFunctionParametersMustBeObject, true);
assert.equal(contract.responsesApi.toolsFunctionParametersTypeMustBeObject, true);
assert.equal(contract.responsesApi.toolsFunctionParametersPropertiesMustBeObject, true);
assert.equal(contract.responsesApi.toolsFunctionParametersRequiredMustBeStringArray, true);
assert.deepEqual(contract.responsesApi.toolChoiceAllowedTypes, ['string', 'object']);
assert.deepEqual(contract.responsesApi.toolChoiceStringValues, ['auto', 'none', 'required']);
assert.equal(contract.responsesApi.toolChoiceRequiredNeedsTools, true);
assert.equal(contract.responsesApi.toolChoiceObjectMustUseFunctionType, true);
assert.equal(contract.responsesApi.toolChoiceObjectRequiresFunctionName, true);
assert.equal(contract.responsesApi.toolChoiceObjectRequiresTools, true);
assert.equal(contract.responsesApi.toolChoiceObjectMustReferenceDeclaredTool, true);
assert.equal(contract.responsesApi.emptyBodyUsesResponsesErrorShape, true);
assert.equal(contract.responsesApi.invalidJsonUsesResponsesErrorShape, true);
assert.equal(contract.responsesApi.goldenCasesImplemented, true);
assert.deepEqual(contract.responsesApi.responseRequiredFields, ['id', 'object', 'created_at', 'model', 'status', 'output', 'usage', 'error', 'incomplete_details']);
assert.deepEqual(contract.responsesApi.errorRequiredFields, ['code', 'type', 'message']);
assert.deepEqual(contract.responsesApi.streamEventOrder, ['response.created', 'response.output_text.delta', 'response.completed']);
assert.equal(contract.responsesApi.rootCapabilitiesPath, '/');
assert.equal(contract.responsesApi.rootCapabilitiesAdvertisesResponsesEndpoints, true);
assert.equal(contract.responsesApi.deleteResponseMethodReturns405, true);
assert.equal(contract.responsesApi.streamSetupUnavailableDegradesToCompleted, true);
assert.equal(contract.responsesApi.streamSetupUnavailableUsesDegradedMessage, true);
assert.equal(contract.responsesApi.streamSetupUnavailableStoredAsCompleted, true);
assert.equal(contract.responsesApi.streamSetupUnavailableRetrievableById, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableDegradesToCompleted, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableUsesDegradedMessage, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableStoredAsCompleted, true);
assert.equal(contract.responsesApi.nonStreamSetupUnavailableRetrievableById, true);
assert.ok(protocolSource.includes('editor-capability-matrix.json'));
assert.ok(apiSource.includes('defaultRuntimeBaseUrl'));
assert.ok(tauriSource.includes('capability_matrix()'));
assert.ok(tauriSource.includes('contract.runtime.health_path'));
assert.ok(tauriSource.includes('contract.openai.models_path'));
assert.deepEqual(contract.errors.requestErrorKinds, ['PuaViolation', 'BudgetExceeded', 'SandboxBlocked']);
assert.equal(contract.errors.requestErrorContextPrefix, 'acp.handle_request.dispatch');
assert.ok(runtimeOpsSource.includes('rpc_error:{code}:{kind}:{message}'));
assert.ok(runtimeOpsSource.includes('acp.handle_request.dispatch'));

console.log('GUI contract smoke passed');
