//! Plan output — structured plan generated by Plan mode, used to hand off
//! to execution modes (Edit, SafeGuard, FullAuto).
//!
//! When the user requests a task in Plan mode, the AI generates a detailed
//! plan as a streaming chat response. This module captures the plan content
//! and extracts structured data (steps, risks, recommended execution mode)
//! so the system can seamlessly transition from planning to execution.
//!
//! # Flow
//!
//! 1. User sends task → Plan mode → AI generates plan document
//! 2. `extract_plan_from_response()` parses the plan from the AI response
//! 3. Response includes `plan_output` field with structured plan data
//! 4. Frontend/GUI can show the plan and let user approve
//! 5. On approval, sends new request with `plan_output` + recommended mode

use serde::{Deserialize, Serialize};

/// Structured plan output extracted from a Plan-mode chat response.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PlanOutput {
    /// The full plan text as generated by the AI.
    pub plan_text: String,

    /// Individual steps extracted from the plan (parsed from markdown lists).
    pub steps: Vec<PlanStep>,

    /// Recommended execution mode based on plan complexity and risk.
    /// One of: "edit", "full_auto", "safeguard".
    pub recommended_mode: String,

    /// Risk assessment from the plan analysis (0.0 = safe, 1.0 = critical).
    pub risk_score: f64,

    /// Whether user approval is required before execution.
    pub requires_approval: bool,

    /// Summary/description of what the plan covers.
    pub summary: String,

    /// List of files or resources the plan identified as needing change.
    pub affected_files: Vec<String>,

    /// Estimated complexity (1-10).
    pub complexity: u8,
}

/// A single step within a plan.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PlanStep {
    /// Step number (1-based).
    pub number: usize,

    /// Description of what this step does.
    pub description: String,

    /// Optional tool/action type for this step (e.g. "read", "edit", "test").
    pub action: Option<String>,

    /// Optional target file for this step.
    pub file: Option<String>,

    /// Whether this step has been completed.
    pub completed: bool,
}

/// Extract a structured plan from a Plan-mode chat response.
///
/// Parses the response text to identify:
/// - Markdown headers (##, ###) as section titles
/// - `- [ ]` or `* [ ]` checkboxes as actionable steps
/// - Code blocks as file references
/// - Risk indicators (keywords like "security", "critical", "backup")
///
/// Returns a default (no steps) plan if the response cannot be parsed.
pub fn extract_plan_from_response(response: &str, _mode: &str) -> PlanOutput {
    let mut steps: Vec<PlanStep> = Vec::new();
    let mut affected_files: Vec<String> = Vec::new();
    let mut risk_score: f64 = 0.0;
    let mut summary = String::new();

    let lower = response.to_lowercase();
    let lines: Vec<&str> = response.lines().collect();

    // ── Extract summary from first non-empty paragraph ──────────────
    for line in &lines {
        let trimmed = line.trim();
        if !trimmed.is_empty()
            && !trimmed.starts_with('#')
            && !trimmed.starts_with('-')
            && !trimmed.starts_with('*')
            && !trimmed.starts_with('`')
        {
            summary = trimmed.to_string();
            if summary.len() > 200 {
                summary.truncate(200);
                summary.push_str("...");
            }
            break;
        }
    }

    // ── Extract steps from markdown checkboxes and numbered lists ───
    for line in &lines {
        let trimmed = line.trim();

        // Checkbox: "- [ ] description" or "* [ ] description"
        if let Some(rest) = trimmed
            .strip_prefix("- [ ] ")
            .or_else(|| trimmed.strip_prefix("* [ ] "))
        {
            let desc = rest.trim().to_string();
            let file = extract_file_ref(rest);
            let action = classify_step_action(&desc, rest);
            if let Some(f) = &file {
                if !affected_files.contains(f) {
                    affected_files.push(f.clone());
                }
            }
            steps.push(PlanStep {
                number: steps.len() + 1,
                description: desc,
                action: Some(action),
                file,
                completed: false,
            });
        }

        // Numbered list: "1. description"
        if let Some(rest) = trimmed
            .strip_prefix(|c: char| c.is_ascii_digit())
            .and_then(|s| s.strip_prefix(". "))
        {
            // Only treat as step if line doesn't look like a reference/code
            if !rest.starts_with('`') && !rest.starts_with('[') {
                let desc = rest.trim().to_string();
                let file = extract_file_ref(rest);
                let action = classify_step_action(rest, rest);
                if let Some(f) = &file {
                    if !affected_files.contains(f) {
                        affected_files.push(f.clone());
                    }
                }
                steps.push(PlanStep {
                    number: steps.len() + 1,
                    description: desc,
                    action: Some(action),
                    file,
                    completed: false,
                });
            }
        }
    }

    // Extract file refs from code blocks (``` ... ``` or `file`)
    let mut in_code_block = false;
    for line in &lines {
        let trimmed = line.trim();
        if trimmed.starts_with("```") {
            in_code_block = !in_code_block;
            continue;
        }
        if in_code_block {
            continue;
        }
        // Inline code backtick references like `src/main.rs`
        for part in trimmed.split('`') {
            let part = part.trim();
            if !part.is_empty()
                && (part.contains('/')
                    || part.contains('\\')
                    || part.ends_with(".rs")
                    || part.ends_with(".ts")
                    || part.ends_with(".py")
                    || part.ends_with(".js")
                    || part.ends_with(".go")
                    || part.ends_with(".toml")
                    || part.ends_with(".json")
                    || part.ends_with(".md")
                    || part.ends_with(".yaml")
                    || part.ends_with(".yml")
                    || part.ends_with(".css"))
                && !affected_files.contains(&part.to_string())
            {
                affected_files.push(part.to_string());
            }
        }
    }

    // ── Assess risk score ──────────────────────────────────────────
    let risk_keywords = [
        ("security", 0.8),
        ("critical", 0.9),
        ("backup", 0.3),
        ("migration", 0.5),
        ("delete", 0.7),
        ("remove", 0.6),
        ("database", 0.4),
        ("production", 0.6),
        ("credential", 0.8),
        ("permission", 0.5),
        ("dangerous", 0.8),
        ("irreversible", 0.9),
    ];
    for &(keyword, weight) in &risk_keywords {
        if lower.contains(keyword) {
            risk_score = risk_score.max(weight);
        }
    }

    // ── Estimate complexity ────────────────────────────────────────
    let step_count = steps.len();
    let file_count = affected_files.len();
    let raw_score = (step_count.max(file_count) as f64 * 0.7 + risk_score * 3.0).round();
    let complexity: u8 = (raw_score as u8).clamp(1, 10);

    // ── Determine recommended mode ─────────────────────────────────
    let recommended_mode = if risk_score >= 0.7 {
        "safeguard"
    } else if complexity >= 6 || step_count > 5 {
        "full_auto"
    } else {
        "edit"
    };

    // ── Determine if approval needed ───────────────────────────────
    let requires_approval = risk_score >= 0.5 || complexity >= 7;

    PlanOutput {
        plan_text: response.to_string(),
        steps,
        recommended_mode: recommended_mode.to_string(),
        risk_score,
        requires_approval,
        summary,
        affected_files,
        complexity,
    }
}

/// Extract a file path reference from a line of text.
fn extract_file_ref(text: &str) -> Option<String> {
    // Look for backtick-quoted paths like `src/main.rs`
    for part in text.split('`') {
        let part = part.trim();
        if part.contains('/')
            && (part.ends_with(".rs")
                || part.ends_with(".ts")
                || part.ends_with(".py")
                || part.ends_with(".js")
                || part.ends_with(".go")
                || part.ends_with(".toml")
                || part.ends_with(".json")
                || part.ends_with(".md")
                || part.ends_with(".css")
                || part.ends_with(".yaml")
                || part.ends_with(".yml"))
        {
            return Some(part.to_string());
        }
    }
    None
}

/// Classify the action type of a plan step.
fn classify_step_action(description: &str, _full_line: &str) -> String {
    let lower = description.to_lowercase();
    if lower.contains("read")
        || lower.contains("review")
        || lower.contains("analyze")
        || lower.contains("inspect")
        || lower.contains("check")
    {
        "read".to_string()
    } else if lower.contains("test")
        || lower.contains("verify")
        || lower.contains("validate")
        || lower.contains("run")
    {
        "test".to_string()
    } else if lower.contains("write")
        || lower.contains("create")
        || lower.contains("add")
        || lower.contains("implement")
        || lower.contains("new ")
    {
        "create".to_string()
    } else if lower.contains("edit")
        || lower.contains("update")
        || lower.contains("modify")
        || lower.contains("change")
        || lower.contains("refactor")
        || lower.contains("fix")
    {
        "edit".to_string()
    } else if lower.contains("test")
        || lower.contains("verify")
        || lower.contains("validate")
        || lower.contains("check")
    {
        "test".to_string()
    } else if lower.contains("delete") || lower.contains("remove") || lower.contains("drop") {
        "delete".to_string()
    } else if lower.contains("search") || lower.contains("find") || lower.contains("grep") {
        "search".to_string()
    } else {
        "execute".to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_empty_response() {
        let plan = extract_plan_from_response("", "plan");
        assert!(plan.steps.is_empty());
        assert_eq!(plan.recommended_mode, "edit");
        assert!(!plan.requires_approval);
    }

    #[test]
    fn test_extract_checkbox_steps() {
        let response = "\
Plan for implementing login feature:

- [ ] Read existing auth module `src/auth.rs`
- [ ] Add login form component `src/ui/login.rs`
- [ ] Update routing `src/router.rs`
- [ ] Test the implementation";
        let plan = extract_plan_from_response(response, "plan");
        assert_eq!(plan.steps.len(), 4);
        assert_eq!(plan.steps[0].action.as_deref(), Some("read"));
        assert_eq!(plan.steps[1].action.as_deref(), Some("create"));
        assert_eq!(plan.steps[2].action.as_deref(), Some("edit"));
        assert_eq!(plan.steps[3].action.as_deref(), Some("test"));
        assert!(plan.affected_files.len() >= 3);
        assert!(plan.affected_files.contains(&"src/auth.rs".to_string()));
    }

    #[test]
    fn test_safeguard_for_security_plan() {
        let response = "\
Plan for rotating API credentials:

- [ ] Backup current config `config/production.toml`
- [ ] Generate new API key
- [ ] Update credential store `config/credentials.toml`
- [ ] Deploy to production";
        let plan = extract_plan_from_response(response, "plan");
        assert_eq!(plan.recommended_mode, "safeguard");
        assert!(plan.requires_approval);
        assert!(plan.risk_score >= 0.5);
    }

    #[test]
    fn test_full_auto_for_complex_plan() {
        let mut response = String::from("Plan for large refactor:\n\n");
        for i in 1..=8 {
            response.push_str(&format!("- [ ] Step {} refactoring module {}\n", i, i));
        }
        let plan = extract_plan_from_response(&response, "plan");
        assert!(plan.complexity >= 6 || plan.recommended_mode == "full_auto");
    }

    #[test]
    fn test_plan_output_serde_roundtrip() {
        let plan = PlanOutput {
            plan_text: "test plan".to_string(),
            steps: vec![PlanStep {
                number: 1,
                description: "Do something".to_string(),
                action: Some("edit".to_string()),
                file: Some("src/main.rs".to_string()),
                completed: false,
            }],
            recommended_mode: "edit".to_string(),
            risk_score: 0.2,
            requires_approval: false,
            summary: "A test plan".to_string(),
            affected_files: vec!["src/main.rs".to_string()],
            complexity: 3,
        };
        let json = serde_json::to_value(&plan).unwrap();
        let deserialized: PlanOutput = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized.recommended_mode, "edit");
        assert_eq!(deserialized.steps.len(), 1);
    }

    #[test]
    fn test_extract_from_plan_mode_only() {
        // Non-plan mode should still produce a plan if content matches
        let response = "\
Here's my analysis:
- [ ] Check the database schema
- [ ] Update the migration script";
        let plan = extract_plan_from_response(response, "edit");
        assert_eq!(plan.steps.len(), 2);
    }

    #[test]
    fn test_action_classification() {
        assert_eq!(classify_step_action("Read the config file", ""), "read");
        assert_eq!(classify_step_action("Create new module", ""), "create");
        assert_eq!(classify_step_action("Fix the bug", ""), "edit");
        assert_eq!(classify_step_action("Test the feature", ""), "test");
        assert_eq!(classify_step_action("Delete old code", ""), "delete");
        assert_eq!(classify_step_action("Search for patterns", ""), "search");
        assert_eq!(classify_step_action("Do something generic", ""), "execute");
    }
}
