---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml

commonLabels:
  app.kubernetes.io/name: go-on
  app.kubernetes.io/component: server

secretGenerator:
  - name: go-on-secrets
    behavior: create
    envs:
      - .secrets.local.env
