//! GAP-B53-57: TripleFusion → EvolutionLoop trigger bridge.
//!
//! Provides a global `mpsc` channel so that triggers generated by the
//! TripleFusion bridge (in the request-handling hot path) are forwarded
//! to the EvolutionLoop (running in a background task).
//!
//! Usage:
//! 1. Call `init_fusion_evolution_bridge()` at startup to obtain the
//!    receiver end, then register it as a trigger source in the loop.
//! 2. Call `send_triggers_to_evolution(triggers)` at each call site
//!    where `run_fusion_cycle()` returns triggers.
//! 3. In the EvolutionLoop, add a `PubsubTriggerSource` wrapping the
//!    receiver.

use crate::orchestration::self_evolution::evolution_loop::EvolutionTrigger;
use std::sync::OnceLock;
use tokio::sync::mpsc;

// ── Global channel ─────────────────────────────────────────────────────────

/// Global sender for forwarding evolution triggers to the EvolutionLoop.
static TRIGGER_SENDER: OnceLock<mpsc::UnboundedSender<EvolutionTrigger>> = OnceLock::new();

// ── Public API ─────────────────────────────────────────────────────────────

/// Initialise the bridge channel and return the receiver end.
///
/// Must be called **once** before the EvolutionLoop starts so the receiver
/// can be wrapped into a `PubsubTriggerSource` and registered.
///
/// Returns an error if called more than once (enforced by `OnceLock`).
pub fn init_fusion_evolution_bridge(
) -> Result<mpsc::UnboundedReceiver<EvolutionTrigger>, &'static str> {
    let (tx, rx) = mpsc::unbounded_channel();
    TRIGGER_SENDER
        .set(tx)
        .map_err(|_| "fusion_evolution_bridge already initialised")?;
    Ok(rx)
}

/// Send a batch of evolution triggers to the EvolutionLoop.
///
/// This is a no-op if the bridge has not been initialised — triggers are
/// silently dropped so the hot path is never blocked.
pub fn send_triggers_to_evolution(triggers: Vec<EvolutionTrigger>) {
    let sender = match TRIGGER_SENDER.get() {
        Some(s) => s,
        None => {
            tracing::warn!(
                target: "fusion_evolution_bridge",
                "bridge not initialised, dropping {} trigger(s)",
                triggers.len()
            );
            return;
        }
    };

    for trigger in triggers {
        if sender.send(trigger).is_err() {
            tracing::warn!(
                target: "fusion_evolution_bridge",
                "failed to send trigger to evolution loop"
            );
        }
    }
}
