//! Built-in provider specifications — single source of truth.
//!
//! This module contains the canonical list of built-in AI provider specs
//! (name, endpoints, key references, capability hints, and recommendation
//! defaults). Both the setup wizard and the config-defaults layer use this
//! single copy instead of maintaining their own duplicates.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::core::config::types::ProviderSpec;

/// Default DeepSeek API base URL — single source shared by the provider spec
/// and the agent-registry fallback.
pub const DEFAULT_DEEPSEEK_BASE: &str = "https://api.deepseek.com";
/// Default DeepSeek model — single source shared by the provider spec and the
/// agent-registry / intel-hub fallbacks.
pub const DEFAULT_DEEPSEEK_MODEL: &str = "deepseek-v4-flash";
/// Default Anthropic API base URL — single source shared by the provider spec
/// and the agent-registry fallback.
pub const DEFAULT_ANTHROPIC_BASE: &str = "https://api.anthropic.com";
/// Default openai_compatible upstream base URL (local Copilot-compatible
/// server) — single source shared by the provider spec and the degraded-mode
/// hint.
pub const DEFAULT_OPENAI_COMPAT_BASE: &str = "http://127.0.0.1:8080/v1";

static PROVIDER_SPECS: OnceLock<Vec<ProviderSpec>> = OnceLock::new();

/// Combined indices for O(1) lookups by name (unique) and agent_type (may have
/// duplicates — values are stored in insertion order to match `.find()` semantics).
type ProviderIndex = (HashMap<String, usize>, HashMap<String, Vec<usize>>);
static PROVIDER_INDEX: OnceLock<ProviderIndex> = OnceLock::new();

/// Returns the full list of built-in provider specs, lazily initialised.
pub fn provider_specs() -> &'static [ProviderSpec] {
    PROVIDER_SPECS
        .get_or_init(built_in_provider_specs)
        .as_slice()
}

fn build_provider_index() -> ProviderIndex {
    let specs = provider_specs();
    let mut name_map = HashMap::with_capacity(specs.len());
    let mut agent_type_map: HashMap<String, Vec<usize>> = HashMap::new();
    for (i, spec) in specs.iter().enumerate() {
        name_map.insert(spec.name.clone(), i);
        agent_type_map
            .entry(spec.agent_type.to_ascii_lowercase())
            .or_default()
            .push(i);
    }
    (name_map, agent_type_map)
}

fn provider_name_index() -> &'static HashMap<String, usize> {
    &PROVIDER_INDEX.get_or_init(build_provider_index).0
}

fn provider_agent_type_index() -> &'static HashMap<String, Vec<usize>> {
    &PROVIDER_INDEX.get_or_init(build_provider_index).1
}

/// Look up a provider spec by the `name` field.
pub fn provider_spec_by_name(name: &str) -> Option<&'static ProviderSpec> {
    let idx = provider_name_index().get(name)?;
    Some(&provider_specs()[*idx])
}

/// Look up a provider spec by the `agent_type` field (case-insensitive).
pub fn provider_spec_by_agent_type(agent_type: &str) -> Option<&'static ProviderSpec> {
    let indices = provider_agent_type_index().get(&agent_type.to_ascii_lowercase())?;
    // Return the first match, preserving the original `.find()` semantics.
    Some(&provider_specs()[indices[0]])
}

fn built_in_provider_specs() -> Vec<ProviderSpec> {
    vec![
        // ── Global Vendors ────────────────────────────────────
        ProviderSpec {
            name: "openai".to_string(),
            agent_type: "openai".to_string(),
            url: Some(crate::shared::http_client::OPENAI_DEFAULT_BASE_URL.to_string()),
            chat_path: None,
            model: Some("gpt-4o-mini".to_string()),
            model_suggestions: vec![
                "gpt-4.1".to_string(),
                "gpt-4.1-mini".to_string(),
                "gpt-4.1-nano".to_string(),
                "o3-mini".to_string(),
                "gpt-4o".to_string(),
                "gpt-4o-mini".to_string(),
                "gpt-4-turbo".to_string(),
                "gpt-3.5-turbo".to_string(),
            ],
            api_key_env: Some("keyring://go-on/openai_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: Some(true),
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(150),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(24),
            recommended_global_max_inflight: Some(128),
            recommended_planning_request_timeout_seconds: Some(120),
            recommended_coding_request_timeout_seconds: Some(150),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "openai_compatible".to_string(),
            agent_type: "openai_compatible".to_string(),
            url: Some(crate::core::providers::DEFAULT_OPENAI_COMPAT_BASE.to_string()),
            chat_path: None,
            model: Some("compatible-model".to_string()),
            model_suggestions: vec![],
            api_key_env: Some("keyring://go-on/openai_compatible_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "anthropic".to_string(),
            agent_type: "claude".to_string(),
            url: Some(DEFAULT_ANTHROPIC_BASE.to_string()),
            chat_path: None,
            model: Some("claude-sonnet-4-20250514".to_string()),
            model_suggestions: vec![
                "claude-opus-4-7".to_string(),
                "claude-sonnet-4-6".to_string(),
                "claude-haiku-4-5-20251001".to_string(),
                "claude-3-5-sonnet".to_string(),
                "claude-3-opus".to_string(),
                "claude-3-haiku".to_string(),
            ],
            api_key_env: Some("keyring://go-on/anthropic_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: Some("2023-06-01".to_string()),
            max_tokens: Some(8192),
            supports_system: Some(true),
            supports_vision: Some(true),
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(75),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(96),
            recommended_planning_request_timeout_seconds: Some(140),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(75),
            recommended_delivery_request_timeout_seconds: Some(110),
        },
        ProviderSpec {
            name: "cohere".to_string(),
            agent_type: "cohere".to_string(),
            url: Some("https://api.cohere.ai/v1".to_string()),
            chat_path: None,
            model: Some("command-r-plus-08-2024".to_string()),
            model_suggestions: vec![
                "command-a-03-2025".to_string(),
                "command-a-reasoning-08-2025".to_string(),
                "command-r7b-12-2024".to_string(),
                "command-r-plus-08-2024".to_string(),
                "command-r-08-2024".to_string(),
            ],
            api_key_env: Some("keyring://go-on/cohere_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        // ── Chinese Vendors (16) ────────────────────────────────
        ProviderSpec {
            name: "deepseek".to_string(),
            agent_type: "deepseek".to_string(),
            url: Some(DEFAULT_DEEPSEEK_BASE.to_string()),
            chat_path: None,
            model: Some(DEFAULT_DEEPSEEK_MODEL.to_string()),
            model_suggestions: vec![
                "deepseek-v4-flash".to_string(),
                "deepseek-v4-pro".to_string(),
                "deepseek-r1".to_string(),
            ],
            api_key_env: Some("keyring://go-on/deepseek_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(32),
            recommended_global_max_inflight: Some(128),
            recommended_planning_request_timeout_seconds: Some(110),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "wenxin".to_string(),
            agent_type: "wenxin".to_string(),
            url: None,
            chat_path: None,
            model: Some("ERNIE-4.5-8K".to_string()),
            model_suggestions: vec![
                "ERNIE-4.5-8K".to_string(),
                "ernie-4.0-turbo-8k".to_string(),
                "ernie-3.5-turbo".to_string(),
            ],
            api_key_env: Some("keyring://go-on/wenxin_api_key".to_string()),
            secret_key_env: Some("keyring://go-on/wenxin_secret_key".to_string()),
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(false),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(96),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "qianfan".to_string(),
            agent_type: "qianfan".to_string(),
            url: None,
            chat_path: None,
            model: Some("ERNIE-4.5-8K".to_string()),
            model_suggestions: vec![
                "ERNIE-4.5-8K".to_string(),
                "ernie-4.0-8k".to_string(),
                "ernie-3.5-8k".to_string(),
                "ernie-speed".to_string(),
                "ernie-lite".to_string(),
            ],
            api_key_env: Some("keyring://go-on/qianfan_api_key".to_string()),
            secret_key_env: Some("keyring://go-on/qianfan_secret_key".to_string()),
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "qwen".to_string(),
            agent_type: "qwen".to_string(),
            url: Some("https://dashscope.aliyuncs.com/compatible-mode/v1".to_string()),
            chat_path: None,
            model: Some("qwen-max".to_string()),
            model_suggestions: vec![
                "qwen-max".to_string(),
                "qwen-plus".to_string(),
                "qwen-turbo".to_string(),
                "qwen2.5-72b-instruct".to_string(),
            ],
            api_key_env: Some("keyring://go-on/qwen_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: Some(true),
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "glm".to_string(),
            agent_type: "glm".to_string(),
            url: Some("https://open.bigmodel.cn/api/paas/v4".to_string()),
            chat_path: None,
            model: Some("glm-4-flash".to_string()),
            model_suggestions: vec![
                "glm-4-flash".to_string(),
                "glm-4v".to_string(),
                "glm-4-plus".to_string(),
                "glm-3-turbo".to_string(),
            ],
            api_key_env: Some("keyring://go-on/glm_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "yi".to_string(),
            agent_type: "yi".to_string(),
            url: Some("https://api.lingyiwanwu.com/v1".to_string()),
            chat_path: None,
            model: Some("yi-lightning".to_string()),
            model_suggestions: vec!["yi-lightning".to_string(), "yi-large".to_string()],
            api_key_env: Some("keyring://go-on/yi_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "hunyuan".to_string(),
            agent_type: "hunyuan".to_string(),
            url: Some("https://api.hunyuan.cloud.tencent.com/v1".to_string()),
            chat_path: None,
            model: Some("hunyuan-turbo-latest".to_string()),
            model_suggestions: vec![
                "hunyuan-turbo-latest".to_string(),
                "hunyuan-turbo".to_string(),
                "hunyuan-pro".to_string(),
            ],
            api_key_env: Some("keyring://go-on/hunyuan_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "doubao".to_string(),
            agent_type: "doubao".to_string(),
            url: Some("https://ark.cn-beijing.volces.com/api/v3".to_string()),
            chat_path: Some("/chat/completions".to_string()),
            model: Some("doubao-1.5-pro-256k-250115".to_string()),
            model_suggestions: vec!["doubao-1.5-pro-32k-250115".to_string()],
            api_key_env: Some("keyring://go-on/doubao_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(24),
            recommended_global_max_inflight: Some(96),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "facewall".to_string(),
            agent_type: "facewall".to_string(),
            url: Some("https://api.facewall.ai/v1".to_string()),
            chat_path: None,
            model: Some("facewall-chat".to_string()),
            model_suggestions: vec![
                "facewall-chat".to_string(),
                "facewall-chat-large".to_string(),
            ],
            api_key_env: Some("keyring://go-on/facewall_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "langboat".to_string(),
            agent_type: "langboat".to_string(),
            url: Some("https://api.langboat.com/v1".to_string()),
            chat_path: None,
            model: Some("langboat-chat".to_string()),
            model_suggestions: vec![
                "langboat-chat".to_string(),
                "langboat-chat-large".to_string(),
            ],
            api_key_env: Some("keyring://go-on/langboat_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "skywork".to_string(),
            agent_type: "skywork".to_string(),
            url: Some("https://api.skywork.ai/v1".to_string()),
            chat_path: None,
            model: Some("skywork-chat".to_string()),
            model_suggestions: vec!["skywork-chat".to_string(), "skywork-chat-large".to_string()],
            api_key_env: Some("keyring://go-on/skywork_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "stepfun".to_string(),
            agent_type: "stepfun".to_string(),
            url: Some("https://api.stepfun.com/v1".to_string()),
            chat_path: None,
            model: Some("step-2-16k".to_string()),
            model_suggestions: vec![
                "step-2-16k".to_string(),
                "step-1-8k".to_string(),
                "step-1-flash".to_string(),
            ],
            api_key_env: Some("keyring://go-on/stepfun_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "xihu".to_string(),
            agent_type: "xihu".to_string(),
            url: Some("https://api.xihu.ai/v1".to_string()),
            chat_path: None,
            model: Some("xihu-chat".to_string()),
            model_suggestions: vec!["xihu-chat".to_string(), "xihu-chat-large".to_string()],
            api_key_env: Some("keyring://go-on/xihu_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "moonshot".to_string(),
            agent_type: "moonshot".to_string(),
            url: Some("https://api.moonshot.cn/v1".to_string()),
            chat_path: None,
            model: Some("moonshot-v1-8k".to_string()),
            model_suggestions: vec![
                "moonshot-v1-8k".to_string(),
                "moonshot-v1-32k".to_string(),
                "moonshot-v1-128k".to_string(),
            ],
            api_key_env: Some("keyring://go-on/moonshot_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        ProviderSpec {
            name: "minimax".to_string(),
            agent_type: "minimax".to_string(),
            url: Some("https://api.minimax.chat/v1".to_string()),
            chat_path: None,
            model: Some("MiniMax-Text-01".to_string()),
            model_suggestions: vec![
                "MiniMax-Text-01".to_string(),
                "MiniMax-Text-01-mini".to_string(),
            ],
            api_key_env: Some("keyring://go-on/minimax_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        // ── Kimi / 月之暗面 ────────────────────────────────
        ProviderSpec {
            name: "kimi".to_string(),
            agent_type: "kimi".to_string(),
            url: Some("https://api.moonshot.cn/v1".to_string()),
            chat_path: None,
            model: Some("kimi-k2.6".to_string()),
            model_suggestions: vec![
                "kimi-k2.6".to_string(),
                "kimi-k2.5".to_string(),
                "kimi-k2".to_string(),
                "kimi-k2-thinking".to_string(),
                "moonshot-v1".to_string(),
            ],
            api_key_env: Some("keyring://go-on/kimi_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(180),
            recommended_review_timeout_seconds: Some(90),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(160),
            recommended_coding_request_timeout_seconds: Some(180),
            recommended_review_request_timeout_seconds: Some(90),
            recommended_delivery_request_timeout_seconds: Some(120),
        },
        // ── SiliconFlow / 硅基流动 ────────────────────────
        ProviderSpec {
            name: "siliconflow".to_string(),
            agent_type: "openai_compatible".to_string(),
            url: Some("https://api.siliconflow.cn/v1".to_string()),
            chat_path: None,
            model: Some("deepseek-ai/DeepSeek-V3.2".to_string()),
            model_suggestions: vec![
                "deepseek-ai/DeepSeek-V3.2".to_string(),
                "deepseek-ai/DeepSeek-R1".to_string(),
                "deepseek-ai/DeepSeek-V2.5".to_string(),
                "Qwen/Qwen2.5-72B-Instruct-128K".to_string(),
                "Qwen/Qwen2.5-32B-Instruct".to_string(),
                "Qwen/QwQ-32B".to_string(),
                "TeleAI/TeleChat-T2".to_string(),
                "THUDM/glm-4-9b-chat".to_string(),
                "internlm/internlm2_5-20b-chat".to_string(),
            ],
            api_key_env: Some("keyring://go-on/siliconflow_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: Some(true),
            region: Some("China".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(32),
            recommended_global_max_inflight: Some(128),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        // ── Other Vendors (15) ──────────────────────────────────
        ProviderSpec {
            name: "ai21".to_string(),
            agent_type: "ai21".to_string(),
            url: Some("https://api.ai21.com/studio/v1".to_string()),
            chat_path: None,
            model: Some("jamba-1.5-mini".to_string()),
            model_suggestions: vec!["jamba-1.5-mini".to_string(), "jamba-1.5-large".to_string()],
            api_key_env: Some("keyring://go-on/ai21_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "aleph".to_string(),
            agent_type: "aleph".to_string(),
            url: Some("https://api.aleph-alpha.com".to_string()),
            chat_path: None,
            model: Some("luminous-base".to_string()),
            model_suggestions: vec!["luminous-base".to_string(), "luminous-extended".to_string()],
            api_key_env: Some("keyring://go-on/aleph_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "copilot".to_string(),
            agent_type: "copilot".to_string(),
            url: Some("https://api.githubcopilot.com".to_string()),
            chat_path: None,
            model: None,
            model_suggestions: vec![
                "claude-opus-4".to_string(),
                "claude-sonnet-4".to_string(),
                "gemini-2.5-pro".to_string(),
                "gpt-5".to_string(),
                "gpt-4.1".to_string(),
                "gpt-4o".to_string(),
                "o1".to_string(),
                "o3-mini".to_string(),
                "gpt-5-mini".to_string(),
                "gpt-4.1-mini".to_string(),
                "gpt-4o-mini".to_string(),
                "claude-3.5-sonnet".to_string(),
                "gemini-2.0-flash-001".to_string(),
            ],
            api_key_env: Some("keyring://go-on/copilot_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(24),
            recommended_global_max_inflight: Some(128),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "deepquest".to_string(),
            agent_type: "deepquest".to_string(),
            url: Some("https://api.deepquest.ai/v1".to_string()),
            chat_path: None,
            model: Some("deepquest-chat".to_string()),
            model_suggestions: vec![
                "deepquest-chat".to_string(),
                "deepquest-chat-large".to_string(),
            ],
            api_key_env: Some("keyring://go-on/deepquest_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "fireworks".to_string(),
            agent_type: "fireworks".to_string(),
            url: Some("https://api.fireworks.ai/inference/v1".to_string()),
            chat_path: None,
            model: Some("accounts/fireworks/models/llama-v3p1-8b-instruct".to_string()),
            model_suggestions: vec![
                "accounts/fireworks/models/llama-v3p1-8b-instruct".to_string(),
                "accounts/fireworks/models/llama-v3p1-405b-instruct".to_string(),
                "accounts/fireworks/models/mixtral-8x22b-instruct".to_string(),
            ],
            api_key_env: Some("keyring://go-on/fireworks_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "gemini".to_string(),
            agent_type: "gemini".to_string(),
            url: Some("https://generativelanguage.googleapis.com/v1beta".to_string()),
            chat_path: None,
            model: Some("gemini-2.5-flash".to_string()),
            model_suggestions: vec![
                "gemini-2.5-flash".to_string(),
                "gemini-2.5-flash-lite".to_string(),
                "gemini-2.5-pro".to_string(),
                "gemini-3.1-pro-preview-03-2026".to_string(),
                "gemini-3-flash-preview-03-2026".to_string(),
                "gemini-2.0-flash".to_string(),
                "gemini-2.0-pro".to_string(),
            ],
            api_key_env: Some("keyring://go-on/gemini_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: Some(true),
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "groq".to_string(),
            agent_type: "groq".to_string(),
            url: Some("https://api.groq.com/openai/v1".to_string()),
            chat_path: None,
            model: Some("llama-3.3-70b-versatile".to_string()),
            model_suggestions: vec![
                "llama-3.3-70b-versatile".to_string(),
                "llama-3.1-8b-instant".to_string(),
                "openai/gpt-oss-120b".to_string(),
                "qwen/qwen3-32b".to_string(),
            ],
            api_key_env: Some("keyring://go-on/groq_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(24),
            recommended_global_max_inflight: Some(96),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "llama".to_string(),
            agent_type: "llama".to_string(),
            url: Some("http://127.0.0.1:11434/v1".to_string()),
            chat_path: None,
            model: Some("llama3.2".to_string()),
            model_suggestions: vec!["llama3.2".to_string(), "llama3.2-vision".to_string()],
            api_key_env: None,
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "loopai".to_string(),
            agent_type: "loopai".to_string(),
            url: Some("https://api.loopai.com/v1".to_string()),
            chat_path: None,
            model: Some("loopai-chat".to_string()),
            model_suggestions: vec!["loopai-chat".to_string(), "loopai-chat-pro".to_string()],
            api_key_env: Some("keyring://go-on/loopai_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "mistral".to_string(),
            agent_type: "mistral".to_string(),
            url: Some("https://api.mistral.ai/v1".to_string()),
            chat_path: None,
            model: Some("mistral-small-latest".to_string()),
            model_suggestions: vec![
                "mistral-large-2512".to_string(),
                "mistral-medium-2508".to_string(),
                "mistral-small-2603".to_string(),
            ],
            api_key_env: Some("keyring://go-on/mistral_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "nim".to_string(),
            agent_type: "nim".to_string(),
            url: Some("https://integrate.api.nvidia.com/v1".to_string()),
            chat_path: None,
            model: Some("meta/llama-3.1-70b-instruct".to_string()),
            model_suggestions: vec![
                "meta/llama-3.1-70b-instruct".to_string(),
                "meta/llama-3.1-405b-instruct".to_string(),
                "mistralai/mixtral-8x22b-instruct".to_string(),
            ],
            api_key_env: Some("keyring://go-on/nim_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "perplexity".to_string(),
            agent_type: "perplexity".to_string(),
            url: Some("https://api.perplexity.ai".to_string()),
            chat_path: None,
            model: Some("sonar-pro".to_string()),
            model_suggestions: vec![
                "sonar-pro".to_string(),
                "sonar".to_string(),
                "sonar-reasoning-pro".to_string(),
                "sonar-deep-research".to_string(),
            ],
            api_key_env: Some("keyring://go-on/perplexity_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        ProviderSpec {
            name: "replicate".to_string(),
            agent_type: "replicate".to_string(),
            url: Some("https://api.replicate.com/v1".to_string()),
            chat_path: None,
            model: Some("meta/meta-llama-3-70b-instruct".to_string()),
            model_suggestions: vec![
                "meta/meta-llama-3-70b-instruct".to_string(),
                "meta/meta-llama-3-8b-instruct".to_string(),
            ],
            api_key_env: Some("keyring://go-on/replicate_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "titan".to_string(),
            agent_type: "titan".to_string(),
            url: Some("https://api.titanml.co/v1".to_string()),
            chat_path: None,
            model: Some("titan-chat".to_string()),
            model_suggestions: vec![
                "amazon.titan-text-premier-v1:0".to_string(),
                "amazon.titan-text-express-v1".to_string(),
            ],
            api_key_env: Some("keyring://go-on/titan_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: None,
            recommended_request_timeout_seconds: None,
            recommended_review_timeout_seconds: None,
            recommended_cache_enabled: None,
            recommended_vector_enabled: None,
            recommended_phase_max_inflight: None,
            recommended_global_max_inflight: None,
            recommended_planning_request_timeout_seconds: None,
            recommended_coding_request_timeout_seconds: None,
            recommended_review_request_timeout_seconds: None,
            recommended_delivery_request_timeout_seconds: None,
        },
        ProviderSpec {
            name: "together".to_string(),
            agent_type: "together".to_string(),
            url: Some("https://api.together.xyz/v1".to_string()),
            chat_path: None,
            model: Some("meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo".to_string()),
            model_suggestions: vec![
                "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo".to_string(),
                "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo".to_string(),
                "mistralai/Mixtral-8x22B-Instruct-v0.1".to_string(),
            ],
            api_key_env: Some("keyring://go-on/together_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: None,
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
        // ── X.AI / Grok ──────────────────────────────────────
        ProviderSpec {
            name: "xai".to_string(),
            agent_type: "openai_compatible".to_string(),
            url: Some("https://api.x.ai/v1".to_string()),
            chat_path: None,
            model: Some("grok-3".to_string()),
            model_suggestions: vec!["grok-2".to_string(), "grok-3".to_string()],
            api_key_env: Some("keyring://go-on/xai_api_key".to_string()),
            secret_key_env: None,
            anthropic_version: None,
            max_tokens: None,
            supports_system: Some(true),
            supports_vision: None,
            region: Some("Global".to_string()),
            recommended_default_phase: Some("coding".to_string()),
            recommended_request_timeout_seconds: Some(120),
            recommended_review_timeout_seconds: Some(60),
            recommended_cache_enabled: Some(true),
            recommended_vector_enabled: Some(true),
            recommended_phase_max_inflight: Some(16),
            recommended_global_max_inflight: Some(64),
            recommended_planning_request_timeout_seconds: Some(100),
            recommended_coding_request_timeout_seconds: Some(120),
            recommended_review_request_timeout_seconds: Some(60),
            recommended_delivery_request_timeout_seconds: Some(90),
        },
    ]
}
